# docker-composeのバージョン選択
version: '3'
services:
  # サービス名
  frontend:
    # Dockerfileの設定
    build:
      # Dockerfileを置いているディレクトリ
      context: .
      # Dockerfileのファイル名
      dockerfile: Dockerfile
    # 作業ディレクトリ
    working_dir: /app
    environment: # 環境変数
      - HOST=0.0.0.0 # localhost接続をする際に必要
      - CHOKIDAR_USEPOLLING=true # ホットリロードを可能にする
    volumes:
      - ./:/app:cached
      # コンテナ内のnode_modulesを指定
      - /app/node_modules
    # コンテナを正常終了するのを防ぐ
    # https://zenn.dev/hohner/articles/43a0da20181d34
    tty: true
    # 公開用のポート指定。ホスト側:コンテナ側
    ports:
      - '5174:5173'
    command: yarn dev # viteの実行コマンド
volumes:
  # ホスト側のnode_modulesをコンテナ側にマウントする
  node_modules:
